library(reshape)
scal_dat=read.table('../REALLY_All_Scaled_Data_with_Missing_Vals.txt', head=T, sep="\t")
scal_dat$Date=as.Date(as.character(scal_dat$Date))
agg_vars=c("ATRCT","AVBLS","ETRAV","NADDU","NTRAN","NTRBL","NTREP","TOUTV","TRFEE")
curr_vars=c("JPY_Rate","GBP_Rate","CHF_Rate","EUR_Rate","CNY_Rate","CAD_Rate","SEK_Rate")
usbtc_dat=data.frame(Date=scal_dat$Date, BTCx=scal_dat$USD_Scaled_Price)